name: Deploy Go Fiber App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    
    - name: Build the Application
      run: |
        go mod tidy
        go build -o gotinder
    
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: gotinder
        path: ./gotinder

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
    - name: Download Binary
      uses: actions/download-artifact@v3
      with:
        name: gotinder
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        script: |
          # Stop the running applications
          pkill gotinder || true

          # Update the binary
          mkdir -p /root/go/gotinder
          cp gotinder /root/go/gotinder/
          chmod +x /root/go/gotinder/gotinder

          # Restart the application
          nohup /root/go/gotinder/gotinder > /root/go/gotinder/app.log 2>&1 &
