name: Deploy Go Fiber App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    
    - name: Build the Application
      run: |
        go mod tidy
        go build -o tinder-backend
    
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: tinder-backend
        path: ./tinder-backend

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
    - name: Download Binary
      uses: actions/download-artifact@v3
      with:
        name: tinder-backend
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        source: /home/runner/work/tinder-backend/tinder-backend
        target: /root/go/gotinder/
        script: |
          # Stop the running application
          pkill tinder-backend || true

          # Update the binary
          mkdir -p /root/go/gotinder
          cp /home/runner/work/tinder-backend/tinder-backend /root/go/gotinder/
          chmod +x /root/go/gotinder/tinder-backend

          # Restart the application
          nohup /root/go/gotinder/tinder-backend > /root/go/gotinder/app.log 2>&1 &
